_core:
  default_config_hash: WCFqLQAxMw1weToDJEhfnW1Z-iOF7cqMdL8X7YTFxBA
icon_base_uri: 'public://media-icons/generic'
iframe_domain: 'https://www.youtube.com/'
oembed_providers_url: 'https://oembed.com/providers.json'
standalone_url: true
